// 所有的事件类型枚举
export var RENDERERMANAGER;
(function (RENDERERMANAGER) {
    RENDERERMANAGER["RENDER"] = "render";
    RENDERERMANAGER["PLAY"] = "play";
    RENDERERMANAGER["STOP"] = "stop";
})(RENDERERMANAGER || (RENDERERMANAGER = {}));
export var SCENESTATUSMANAGER;
(function (SCENESTATUSMANAGER) {
    SCENESTATUSMANAGER["HOVERCHANGE"] = "hover-change";
    SCENESTATUSMANAGER["ACTIVECHANGE"] = "active-change";
})(SCENESTATUSMANAGER || (SCENESTATUSMANAGER = {}));
export var POINTERMANAGER;
(function (POINTERMANAGER) {
    POINTERMANAGER["POINTERDOWN"] = "pointerdown";
    POINTERMANAGER["POINTERMOVE"] = "pointermove";
    POINTERMANAGER["POINTERUP"] = "pointerup";
})(POINTERMANAGER || (POINTERMANAGER = {}));
export var MODELCOMPILER;
(function (MODELCOMPILER) {
    MODELCOMPILER["SETMATERIAL"] = "setMaterial";
})(MODELCOMPILER || (MODELCOMPILER = {}));
export var LOADERMANAGER;
(function (LOADERMANAGER) {
    LOADERMANAGER["LOADING"] = "loading";
    LOADERMANAGER["DETAILLOADING"] = "detailLoading";
    LOADERMANAGER["DETAILLOADED"] = "detailLoaded";
    LOADERMANAGER["LOADED"] = "loaded";
})(LOADERMANAGER || (LOADERMANAGER = {}));
export const EVENTTYPE = {
    RENDERERMANAGER,
    SCENESTATUSMANAGER,
    POINTERMANAGER,
    MODELCOMPILER,
    LOADERMANAGER
};
//# sourceMappingURL=EVENTTYPE.js.map