import { MODULETYPE } from "./MODULETYPE";
export declare const CONFIGMODULE: {
    ImageTexture: MODULETYPE;
    CubeTexture: MODULETYPE;
    CanvasTexture: MODULETYPE;
    VideoTexture: MODULETYPE;
    MeshStandardMaterial: MODULETYPE;
    MeshPhongMaterial: MODULETYPE;
    SpriteMaterial: MODULETYPE;
    LineBasicMaterial: MODULETYPE;
    PointsMaterial: MODULETYPE;
    AmbientLight: MODULETYPE;
    SpotLight: MODULETYPE;
    PointLight: MODULETYPE;
    DirectionalLight: MODULETYPE;
    BoxGeometry: MODULETYPE;
    SphereGeometry: MODULETYPE;
    LoadGeometry: MODULETYPE;
    PlaneGeometry: MODULETYPE;
    CircleGeometry: MODULETYPE;
    ConeGeometry: MODULETYPE;
    EdgesGeometry: MODULETYPE;
    Sprite: MODULETYPE;
    Line: MODULETYPE;
    Mesh: MODULETYPE;
    Points: MODULETYPE;
    Group: MODULETYPE;
    PerspectiveCamera: MODULETYPE;
    OrthographicCamera: MODULETYPE;
    WebGLRenderer: MODULETYPE;
    Scene: MODULETYPE;
    TransformControls: MODULETYPE;
    OrbitControls: MODULETYPE;
    SMAAPass: MODULETYPE;
    UnrealBloomPass: MODULETYPE;
};
