export declare enum CONFIGTYPE {
    BOXGEOMETRY = "BoxGeometry",
    SPHEREGEOMETRY = "SphereGeometry",
    LOADGEOMETRY = "LoadGeometry",
    MODEL = "Model",
    SPRITE = "Sprite",
    IMAGETEXTURE = "ImageTexture",
    CUBETEXTURE = "CubeTexture",
    CANVASTEXTURE = "CanvasTexture",
    MESHSTANDARDMATERIAL = "MeshStandardMaterial",
    MESHPHONGMATERIAL = "MeshPhongMaterial",
    SPRITEMATERIAL = "SpriteMaterial",
    AMBIENTLIGHT = "AmbientLight",
    SPOTLIGHT = "SpotLight",
    POINTLIGHT = "PointLight",
    PERSPECTIVECAMERA = "PerspectiveCamera",
    ORTHOGRAPHICCAMERA = "OrthographicCamera",
    WEBGLRENDERER = "WebGLRenderer",
    SCENE = "Scene",
    TRNASFORMCONTROLS = "TransformControls",
    ORBITCONTROLS = "OrbitControls"
}
