export var PASS_CONFIGTYPE;
(function (PASS_CONFIGTYPE) {
    PASS_CONFIGTYPE["SMAAPASS"] = "SMAAPass";
    PASS_CONFIGTYPE["UNREALBLOOMPASS"] = "UnrealBloomPass";
    PASS_CONFIGTYPE["SELECTIVEBLOOMPASS"] = "SelectiveBloomPass";
    PASS_CONFIGTYPE["SSAOPASS"] = "SSAOPass";
})(PASS_CONFIGTYPE || (PASS_CONFIGTYPE = {}));
