import { ObjectEvent } from "../../manager/EventManager";
import { CONFIGTYPE } from "../../middleware/constants/CONFIGTYPE";
export declare const onComputed: (fun: () => any) => symbol;
export declare const onEvent: (fun: (event?: ObjectEvent) => void) => {
  name: symbol;
};
export declare const createElement: (
  type: CONFIGTYPE,
  merge: any
) =>
  | import("../../middleware/object/ObjectConfig").ObjectConfig
  | import("../../middleware/light/LightConfig").LightConifg
  | import("../../middleware/light/LightConfig").PointLightConfig
  | import("../../middleware/light/LightConfig").SpotLightConfig
  | import("../../middleware/light/LightConfig").DirectionalLightConfig
  | import("../../middleware/light/LightConfig").HemisphereLightConfig
  | import("../../middleware/light/LightConfig").RectAreaLightConfig
  | import("../../middleware/geometry/GeometryInterface").BoxGeometryConfig
  | import("../../middleware/geometry/GeometryInterface").SphereGeometryConfig
  | import("../../middleware/geometry/GeometryInterface").PlaneGeometryConfig
  | import("../../middleware/geometry/GeometryInterface").CircleGeometryConfig
  | import("../../middleware/geometry/GeometryInterface").ConeGeometryConfig
  | import("../../middleware/geometry/GeometryInterface").LoadGeometryConfig
  | import("../../middleware/geometry/GeometryInterface").CylinderGeometryConfig
  | import("../../middleware/geometry/GeometryInterface").DodecahedronGeometryConfig
  | import("../../middleware/geometry/GeometryInterface").EdgesGeometryConfig
  | import("../../middleware/geometry/GeometryInterface").TorusGeometryConfig
  | import("../../middleware/geometry/GeometryInterface").RingGeometryConfig
  | import("../../middleware/geometry/GeometryInterface").CustomGeometryConfig
  | import("../../middleware/geometry/GeometryInterface").LineCurveGeometryConfig
  | import("../../middleware/geometry/GeometryInterface").SplineCurveGeometryConfig
  | import("../../middleware/geometry/GeometryInterface").CubicBezierCurveGeometryConfig
  | import("../../middleware/geometry/GeometryInterface").QuadraticBezierCurveGeometryConfig
  | import("../../middleware/geometry/GeometryInterface").LineTubeGeometryConfig
  | import("../../middleware/geometry/GeometryInterface").SplineTubeGeometryConfig
  | import("../../middleware/geometry/GeometryInterface").LineShapeGeometryConfig
  | import("../../middleware/texture/TextureConfig").ImageTextureConfig
  | import("../../middleware/texture/TextureConfig").CubeTextureConfig
  | import("../../middleware/texture/TextureConfig").CanvasTextureConfig
  | import("../../middleware/texture/TextureConfig").LoadTextureConfig
  | import("../../middleware/material/MaterialConfig").MeshBasicMaterialConfig
  | import("../../middleware/material/MaterialConfig").MeshStandardMaterialConfig
  | import("../../middleware/material/MaterialConfig").MeshPhongMaterialConfig
  | import("../../middleware/material/MaterialConfig").SpriteMaterialConfig
  | import("../../middleware/material/MaterialConfig").LineBasicMaterialConfig
  | import("../../middleware/material/MaterialConfig").PointsMaterialConfig
  | import("../../middleware/material/MaterialConfig").ShaderMaterialConfig
  | import("../../middleware/material/MaterialConfig").MeshPhysicalMaterialConfig
  | import("../../middleware/camera/CameraConfig").PerspectiveCameraConfig
  | import("../../middleware/camera/CameraConfig").OrthographicCameraConfig
  | import("../../middleware/renderer/RendererConfig").WebGLRendererConfig
  | import("../../middleware/renderer/RendererConfig").CSS3DRendererConfig
  | import("../../middleware/scene/SceneConfig").SceneConfig
  | import("../../middleware/controls/ControlsConfig").TransformControlsConfig
  | import("../../middleware/controls/ControlsConfig").OrbitControlsConfig
  | import("../../middleware/sprite/SpriteConfig").SpriteConfig
  | import("../../middleware/mesh/MeshConfig").MeshConfig
  | import("../../middleware/points/PointsConfig").PointsConfig
  | import("../../middleware/line/LineConfig").LineConfig
  | import("../../middleware/group/GroupConfig").GroupConfig
  | import("../../middleware/pass/PassConfig").SMAAPassConfig
  | import("../../middleware/pass/PassConfig").UnrealBloomPassConfig
  | import("../../middleware/pass/PassConfig").SelectiveBloomPassConfig
  | import("../../middleware/pass/PassConfig").SSAOPassConfig
  | import("../../middleware/animation/AnimationConfig").ScriptAnimationConfig
  | import("../../middleware/animation/AnimationConfig").KeyframeAnimationConfig
  | import("../../middleware/css3D/CSS3DConfig").CSS3DObjectConfig
  | import("../../middleware/css3D/CSS3DConfig").CSS3DPlaneConfig
  | import("../../middleware/css3D/CSS3DConfig").CSS3DSpriteConfig
  | import("../../middleware/css2D/CSS2DConfig").CSS2DPlaneConfig;
