import { EngineSupport, EngineSupportParameters } from "@vis-three/middleware";
import { AxesHelper, Event, GridHelper, Object3D, WebGLRenderer } from "three";
import { EffectComposer } from "three/examples/jsm/postprocessing/EffectComposer";
import { CSS2DRenderer } from "three/examples/jsm/renderers/CSS2DRenderer";
import { CSS3DRenderer } from "three/examples/jsm/renderers/CSS3DRenderer";
import { Screenshot, WebGLRendererEngine } from "@vis-three/webgl-renderer-plugin";
import { EffectComposerEngine } from "@vis-three/effect-composer-plugin";
import { OrbitControlsEngine } from "@vis-three/orbit-controls-plugin";
import { SelectionEngine } from "@vis-three/selection-plugin";
import { AxesHelperEngine, AxesHelperOptions } from "@vis-three/axes-helper-plugin";
import { GridHelperEngine } from "@vis-three/grid-helper-plugin";
import { ViewpointEngine } from "@vis-three/viewpoint-plugin";
import { TransformControlsEngine, VisTransformControls } from "@vis-three/transform-controls-plugin";
import { StatsEngine } from "@vis-three/stats-plugin";
import { KeyboardManager, KeyboardManagerEngine } from "@vis-three/keyboard-manager-plugin";
import { ObjectHelperEngine, ObjectHelperManager } from "@vis-three/object-helper-plugin";
import { CSS2DRendererEngine } from "@vis-three/css2d-renderer-plugin";
import { CSS3DRendererEngine } from "@vis-three/css3d-renderer-plugin";
import { VisStats } from "@vis-three/stats-plugin/VisStats";
export declare class ModelingEngineSupport extends EngineSupport implements WebGLRendererEngine, EffectComposerEngine, OrbitControlsEngine, KeyboardManagerEngine, StatsEngine, TransformControlsEngine, ViewpointEngine, GridHelperEngine, AxesHelperEngine, SelectionEngine, ObjectHelperEngine, CSS2DRendererEngine, CSS3DRendererEngine {
    webGLRenderer: WebGLRenderer;
    getScreenshot: (params?: Screenshot | undefined) => Promise<string>;
    effectComposer: EffectComposer;
    orbitControls: any;
    keyboardManager: KeyboardManager;
    stats: VisStats;
    setStats: (show: boolean) => StatsEngine;
    transing: boolean;
    transformControls: VisTransformControls;
    setTransformControls: (show: boolean) => TransformControlsEngine;
    setViewpoint: any;
    gridHelper: GridHelper;
    setGridHelper: (show: boolean) => GridHelperEngine;
    axesHelper: AxesHelper;
    setAxesHelper: (params: AxesHelperOptions) => AxesHelperEngine;
    selectionBox: Set<Object3D<Event>>;
    setSelectionBox: (objects: Object3D<Event>[]) => SelectionEngine;
    objectHelperManager: ObjectHelperManager;
    setObjectHelper: (show: boolean) => ObjectHelperEngine;
    css2DRenderer: CSS2DRenderer;
    css3DRenderer: CSS3DRenderer;
    constructor(parameters?: EngineSupportParameters);
}
